name: Update Config and Run

on:
  workflow_dispatch:
    inputs:
      pull_number:
        description: 'Pull Request Number'
        required: true
      root_directory:
        description: 'Root Directory'
        required: true
        default: './'
      excluded_directories:
        description: 'Excluded Directories (comma-separated)'
        required: true
        default: 'node_modules'
      reviewers:
        description: 'Pull Request Reviewers (comma-separated)'
        required: true

jobs:
  update-and-run:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Update config file
        run: |
          # Convert comma-separated excluded directories to JSON array
          EXCLUDED_DIRS_JSON=$(echo "${{ github.event.inputs.excluded_directories }}" | \
            jq -R 'split(",") | map(trim)')
          
          # Convert comma-separated reviewers to JSON array
          REVIEWERS_JSON=$(echo "${{ github.event.inputs.reviewers }}" | \
            jq -R 'split(",") | map(trim)')
          
          # Update config.json using jq
          jq --arg pn "${{ github.event.inputs.pull_number }}" \
             --arg rd "${{ github.event.inputs.root_directory }}" \
             --argjson ed "${EXCLUDED_DIRS_JSON}" \
             --argjson pr "${REVIEWERS_JSON}" \
             '.repository.pullNumber = ($pn | tonumber) |
              .rootDirectory = $rd |
              .excludedDirectories = $ed |
              .pullRequestReviewers = $pr' \
             src/config/config.json > temp.json && mv temp.json src/config/config.json

      - name: Run start command
        run: pnpm start
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}